/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;

public class App {

    public static void analyzeWeather(int[] weatherArray) {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };


    }

//    public static String tally(List<String> votes) {
//
//        HashSet<String> candidates = new HashSet<>();
//        String winner;
//        for(String vote : votes) {
//            candidates.add(vote);
//        }
//        return vote;
//    }




    public static void main(String[] args) {
//        List<String> votes = new ArrayList<>();
//        votes.add("Bush");
//        votes.add("Bush");
//        votes.add("Bush");
//        votes.add("Shrub");
//        votes.add("Hedge");
//        votes.add("Shrub");
//        votes.add("Bush");
//        votes.add("Hedge");
//        votes.add("Bush");
//
//        String winner = tally(votes);
//        System.out.println(winner + " received the most votes!");

        HashSet<String> iceCreamFlavors = new HashSet<>();
        iceCreamFlavors.add("Bush");
        iceCreamFlavors.add("Bush");
        iceCreamFlavors.add("Bush");
        iceCreamFlavors.add("Shrub");
        iceCreamFlavors.add("Hedge");
        iceCreamFlavors.add("Shrub");
        iceCreamFlavors.add("Bush");
        iceCreamFlavors.add("Hedge");
        iceCreamFlavors.add("Bush");

        for(String iceCream : iceCreamFlavors){
            System.out.println(iceCream);
        }

    }


}
