/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRoll() {
        Library rollTest = new Library();

        ArrayList<Integer> testArray = new ArrayList<>();
        testArray.add(1);
        testArray.add(2);
        testArray.add(3);
        testArray.add(4);

        int expected = testArray.size();
        int actual = rollTest.roll(4).size();

        assertEquals(expected, actual);
    }

    @Test public void testDuplicates() {
        Library duplicatesTest = new Library();

        char[] testArray = {'a', 'b', 'c', 'd', 'e', 'e'};
        
        boolean actual = duplicatesTest.containsDuplicates(testArray);
        assertEquals("There are duplicates in the testArray", true, actual);
    }

    @Test public void testAverage() {
        double[] testArray = {2, 2 ,2 , 2, 2};
        double actual = Library.calculateAverage(testArray);
        double expected = 2.0;


        assertEquals(expected, actual, 0);

    }
}
