/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import javax.lang.model.SourceVersion;
import java.util.ArrayList;
import java.util.HashSet;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRoll() {
        Library rollTest = new Library();

        ArrayList<Integer> testArray = new ArrayList<>();
        testArray.add(1);
        testArray.add(2);
        testArray.add(3);
        testArray.add(4);

        int expected = testArray.size();
        int actual = rollTest.roll(4).size();

        assertEquals(expected, actual);
    }

    @Test public void testDuplicates() {
        Library duplicatesTest = new Library();

        char[] testArray = {'a', 'b', 'c', 'd', 'e', 'e'};
        
        boolean actual = duplicatesTest.containsDuplicates(testArray);
        assertEquals("There are duplicates in the testArray", true, actual);
    }

    @Test public void testAverage() {
        int[] testArray = {2, 2 ,2 , 2, 2};
        int actual = Library.calculateAverage(testArray);
        int expected = 2;


        assertEquals(expected, actual);

    }

    @Test public void testMatrix() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        int[] expected =  new int[] {55, 54, 60, 53, 59, 57, 61};
        for(int number : expected) {
            System.out.println(number);
        }
        int[] actual = Library.getLowestAverageOfMatrix(weeklyMonthTemperatures);
        
        for(int number : actual) {
            System.out.println("number = " + number);
        }
        assertArrayEquals(expected, actual);

    }

    @Test public void testAnalyzeWeather() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        String expected = "High: 72\n" +
        "Low: 51\n" +
        "Never saw temperature: 63\n" +
        "Never saw temperature: 67\n" +
        "Never saw temperature: 68\n" +
        "Never saw temperature: 69\n" ;
        System.out.println("weeklyMonthTemperatures = " + Library.analyzeWeather(weeklyMonthTemperatures));
        String actual =  Library.analyzeWeather(weeklyMonthTemperatures);
        assertEquals(expected, actual);

    }
}
